/******************************************************
 * Behavior implementation file template.             *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "msp430x_isa.H"
#include  "msp430x_isa_init.cpp"
#include  "msp430x_bhv_macros.H"

//!'using namespace' statement to allow access to all msp430x-specific datatypes
using namespace msp430x_parms;

//!Behavior executed before simulation begins.
void ac_behavior( begin ){};

//!Behavior executed after simulation ends.
void ac_behavior( end ){};

//!Generic instruction behavior method.
void ac_behavior( instruction ){};
 
//! Instruction Format behavior methods.
void ac_behavior( Type_DoubleOp ){}
void ac_behavior( Type_SimpleOp ){}
void ac_behavior( Type_Jump ){}
 
//!Instruction MOV behavior method.
void ac_behavior( MOV ){}

//!Instruction ADD behavior method.
void ac_behavior( ADD ){}

//!Instruction ADDC behavior method.
void ac_behavior( ADDC ){}

//!Instruction SUB behavior method.
void ac_behavior( SUB ){}

//!Instruction SUBC behavior method.
void ac_behavior( SUBC ){}

//!Instruction CMP behavior method.
void ac_behavior( CMP ){}

//!Instruction DADD behavior method.
void ac_behavior( DADD ){}

//!Instruction BIT behavior method.
void ac_behavior( BIT ){}

//!Instruction BIC behavior method.
void ac_behavior( BIC ){}

//!Instruction BIS behavior method.
void ac_behavior( BIS ){}

//!Instruction XOR behavior method.
void ac_behavior( XOR ){}

//!Instruction AND behavior method.
void ac_behavior( AND ){}

//!Instruction RRC behavior method.
void ac_behavior( RRC ){}

//!Instruction RRA behavior method.
void ac_behavior( RRA ){}

//!Instruction PUSH behavior method.
void ac_behavior( PUSH ){}

//!Instruction SWPB behavior method.
void ac_behavior( SWPB ){}

//!Instruction CALL behavior method.
void ac_behavior( CALL ){}

//!Instruction RETI behavior method.
void ac_behavior( RETI ){}

//!Instruction SXT behavior method.
void ac_behavior( SXT ){}

//!Instruction JZ behavior method.
void ac_behavior( JZ ){}

//!Instruction JNZ behavior method.
void ac_behavior( JNZ ){}

//!Instruction JC behavior method.
void ac_behavior( JC ){}

//!Instruction JNC behavior method.
void ac_behavior( JNC ){}

//!Instruction JN behavior method.
void ac_behavior( JN ){}

//!Instruction JGE behavior method.
void ac_behavior( JGE ){}

//!Instruction JL behavior method.
void ac_behavior( JL ){}

//!Instruction JMP behavior method.
void ac_behavior( JMP ){}

